### ISSUE TITLE
Consider using a Scala script instead of Bash for `init-slides.sh` example

### ISSUE THREAD

**Issue by spamegg1** [bjornregnell/taggy#7]
Looks like the example requires `scala` (old `scala-cli`) anyway. 

So, might as well use it for the [script itself!](https://scala-cli.virtuslab.org/docs/guides/scripting/scripts#self-executable-scala-script)

- Increases the educational value by having a Scala script example.
- Avoids having to basically copy-paste the Scala script into the Bash script.
  - Could probably avoid having the separate `slides.scala` file too. (Simplifies / removes file checking logic)
- Bash scripts can be fragile depending on the environment, with confusing syntax. Scala can be more consistent (and typed!)

What do you think?

**Comment by spamegg1** [comment]
I'll try to make a PR.

**Comment by bjornregnell** [comment]
Perhaps we should make it work out of the box with the new scala runner and don't require scala-cli? I mean you can run scripts without the she-bang just explicit scala run and then it works on windows which I think would be good.

**Comment by bjornregnell** [comment]
We could call your new script idea `init-taggy.scala` and run it with `scala run init-taggy.scala` and if you prefer that script could `//> using toolkit default` and os-lib for the download so we dont need curl and it will showcase the toolkit and work on all platforms...

**Comment by spamegg1** [comment]
> I mean you can run scripts without the she-bang just explicit scala run and then it works on windows which I think would be good.

OK, didn't think of Windows. AGAIN :sweat_smile: 
Can do that for sure.

> I think we should make it work out of the box with the new scala runner and don't require scala-cli

Just for clarity, the 3.5.0 `scala` runner actually installs `scala-cli` and it's just a wrapper around `scala-cli`. They are in the same directory (at least on Linux). If one is on PATH, the other is too (but I agree we shouldn't rely on that).

> We could call your new script idea init-taggy.scala (a better name than init-slides I think) and run it with scala run init-taggy.scala and that script could //> using toolkit default and os-lib for the download so we dont need curl and it will showcase the toolkit and work on all platforms...

Sure thing, the usage of Toolkit and `os-lib` is OK with your "zero dependency" stance right?

**Comment by bjornregnell** [comment]
> Sure thing, the usage of Toolkit and os-lib is OK with your "zero dependency" stance right?

taggy.scala itself does not require os-lib so that's ok. toolkit is almost stdlib :)

**Comment by bjornregnell** [comment]
As scripts end with .sc and they then don't clobber scala run .   (edited my post above with this name change)

**Comment by bjornregnell** [comment]
> Looks like the example requires scala (old scala-cli) anyway.

Tried to remove it everywhere before release :( Where did I forget to remove it?

**Comment by spamegg1** [comment]
> > Looks like the example requires scala (old scala-cli) anyway.
> 
> Tried to remove it everywhere before release. Where did I forget to remove it?

Maybe it's a miscommunication on my part; I meant that it requires Scala to be already installed on the user's computer. So it's not a "standalone Bash script that secretly installs Scala" for lack of a better term.

```bash
echo "Compiling and running $DEST using scala-cli"
scala-cli run "$DEST"
```
> we should make it work out of the box with the new scala runner and don't require scala-cli

So we are requiring 3.5.0 minimum right? Just to be clear.

**Comment by bjornregnell** [comment]
Cool. Also if your contribution is in `init-taggy.sc` then we can keep a file called `init-slides.sh` for backwards compability/stability of spread instructions...  It's fine that it requires scala installed as thats the whole point: get more to install and try out scala :)

**Comment by bjornregnell** [comment]
https://github.com/bjornregnell/taggy/commit/8ed2b5af249dda7cbbbcf251d0f36b219be62b08
Thanks for the pointer!

**Comment by bjornregnell** [comment]
https://github.com/bjornregnell/taggy/issues/11
